# -*- mode: ruby -*-
# vi: set ft=ruby :
Vagrant.configure("2") do |config|
  config.vm.box = "bento/ubuntu-20.04"

  node_ips = {
    1 => "192.168.56.101",
    2 => "192.168.56.102",
    3 => "192.168.56.103",
    4 => "192.168.56.104"
  }

  (1..4).each do |i|
    config.vm.define "node#{i}" do |node|
      node.vm.hostname = "node#{i}"  # Proper hostname for each node
      node.vm.network "private_network", ip: node_ips[i]
      node.vm.synced_folder "./packages", "/vagrant_data"

      node.vm.provider "virtualbox" do |vb|
        vb.memory = "2048"
        vb.cpus = 2
      end

#      node.vm.provision "shell", inline: "dpkg -i /vagrant_data/nginx_offline.deb"
    end
  end
end
