version: "3.8"
services:
  web:
    image: nginx
    ports:
      - "8080:80"
    deploy:
      replicas: 2
      restart_policy:
        condition: on-failure
    volumes:
      - webdata:/usr/share/nginx/html

volumes:
  webdata:
