version: "3.8"
services:
  web:
    image: nginx
    ports:
      - "8080:80"
    deploy:
      replicas: 2
      restart_policy:
        condition: on-failure
      resources:
        limits:
          memory: 1G
          cpus: "0.1"
      placement:
        constraints:
          - node.labels.A == B
          # - node.role == worker
          # - node.labels.test_node_label == true

    volumes:
      - webdata:/usr/share/nginx/html

volumes:
  webdata:
