global:
  scrape_interval:     30s
  evaluation_interval: 30s
  external_labels:
      monitor: prom

rule_files:
  - /etc/prometheus/alerts/rules.yaml
  - /etc/prometheus/alerts/*.rules

alerting:
  alertmanagers:
  - scheme: http
    static_configs:
    - targets:
        - alertmanager:9093

scrape_configs:
  - job_name: prometheus
    static_configs:
      - targets: ['prometheus:9090']

  - job_name: 'cadvisor'
    static_configs:
      - targets:
        - pod.monlog-server.tamam.one
    scheme: https
    basic_auth:
      username: 'Tamam'
      password: 'azddqmbwvcB8RSDYP8fn2H7UDoq5Vk'

  - job_name: 'node-exporter'
    file_sd_configs:
      - files:
        - '/etc/prometheus/sd-file.yml'
    scheme: https
    basic_auth:
      username: 'Tamam'
      password: 'azddqmbwvcB8RSDYP8fn2H7UDoq5Vk'


  - job_name: 'blackbox_exporter'
    static_configs:
      - targets: ['blackbox-exporter:9115']

  - job_name: 'blackbox-ping'
    scrape_interval: 30s
    metrics_path: /probe
    params:
      module: [icmp_ipv4]
    static_configs:
      - targets:
          - 8.8.8.8
          - google.com
          - node-exporter
          - blackbox-exporter
          - cadvisor
          - pushgateway
          - alertmanager
          - grafana
          - prometheus
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: blackbox-exporter:9115

  - job_name: 'grafana'
    scrape_interval: 30s
    metrics_path: '/metrics'
    static_configs:
      - targets: ['grafana:3000']

  - job_name: 'alertmanager'
    scrape_interval: 30s
    metrics_path: '/metrics'
    static_configs:
      - targets: ['alertmanager:9093']

  - job_name: 'pushgateway'
    scrape_interval: 30s
    metrics_path: '/metrics'
    static_configs:
      - targets: ['pushgateway:9091']

  - job_name: 'traefik'
    metrics_path: '/metrics'
    static_configs:
      - targets:
        - trametr.monlog-server.tamam.ir
        - trametr.repo-server.tamam.ir
        - trametr.tools-server.tamam.ir
        - trametr.elk-server.tamam.ir
        - trametr.production.tamam.ir
        - trametr.pre-production.tamam.ir
        - trametr.development.tamam.ir
    scheme: https
    basic_auth:
      username: 'Tamam'
      password: 'azddqmbwvcB8RSDYP8fn2H7UDoq5Vk'

  - job_name: 'tempo'
    static_configs:
      - targets: [ 'tempo:3200' ]

  - job_name: tamam/mimir
    static_configs:
      - targets: ["mimir1:8080"]
        labels:
          pod: "mimir1"
      - targets: ["mimir2:8080"]
        labels:
          pod: "mimir2"
      - targets: ["mimir3:8080"]
        labels:
          pod: "mimir3"

  - job_name: 'gitlab-ci-pipelines-exporter'
    scrape_interval: 10s
    scrape_timeout: 5s
    static_configs:
      - targets: ['gitlab-ci-pipelines-exporter:8080']

remote_write:
  - url: http://load-balancer:9009/api/v1/push
    # Add X-Scope-OrgID header so that Mimir knows what tenant the remote write data should be stored in.
    # In this case, our tenant is "tamam"
    headers:
      X-Scope-OrgID: tamam
