---
- hosts: repo-servers
  become: true
  gather_facts: yes
  name: install and configure servers
  roles:
    - { role: preparing_server, become: True, tags: preparing_server }
    - { role: docker, become: True, tags: docker_setup }
